#!/usr/bin/env python3
"""Extract AK980 PRO models from ajazz-hub bundle and merge them into models.json/models.ts."""
import os
import re
import json
import glob

import sys

# Try to locate index-*.js from app-hub/js/ or the scratch directory
def find_hub_js():
    explicit = sys.argv[1] if len(sys.argv) > 1 else os.environ.get("HUB_JS")
    if explicit:
        return explicit
    patterns = [
        "app-hub/js/index-*.js",
        "../app-hub/js/index-*.js",
        "/root/.gemini/antigravity-cli/brain/*/scratch/hub_js/index-*.js",
        "**/scratch/hub_js/index-*.js"
    ]
    for pat in patterns:
        hits = sorted(glob.glob(pat, recursive=True))
        if hits:
            return hits[0]
    return None

hub_js_path = find_hub_js()
if not hub_js_path:
    print("Warning: index-*.js of ajazz-hub not found in expected locations.")
    # Create an empty or fallback list of models if file is missing
    hub_models = []
else:
    print(f"Parsing ajazz-hub JS from: {hub_js_path}")
    content = open(hub_js_path, "r", encoding="utf-8", errors="ignore").read()
    
    # We find models matching name:"AK980 PRO", vendorId:3141
    # We will search for all '{name:"AK980 PRO",vendorId:3141' or generic '{name:"...",vendorId:'
    matches = list(re.finditer(r'\{name:"([^"]+)",vendorId:(\d+),productId:(\d+)', content))
    
    hub_models = []
    seen_keys = set()
    for m in matches:
        name = m.group(1)
        vid = int(m.group(2))
        pid = int(m.group(3))
        
        # Avoid duplicate (vid, pid, name)
        key = (vid, pid, name)
        if key in seen_keys:
            continue
        seen_keys.add(key)
        
        # Slice window to find layouts/deviceMode
        start = m.start()
        window = content[start:start+1000] # large enough to capture layout keys
        
        # Find deviceMode
        dm_m = re.search(r'deviceMode:(\d+)', window)
        device_mode = int(dm_m.group(1)) if dm_m else 0
        
        # Simple estimation of connection type
        connect = "USB"
        if pid in (32839, 32790):
            connect = "2.4G"
        elif pid == 32835:
            connect = "USB"
            
        hub_models.append({
            "vendorId": vid,
            "productId": pid,
            "name": name,
            "supplierName": "ajazz",
            "connectType": connect,
            "routesName": ["customKeys", "lighting", "macro", "tft", "settings"],
            "keyboardImg": "AK980_PRO.png",
            "driverSource": "hub",
            "deviceMode": device_mode
        })

print(f"Extracted {len(hub_models)} model(s) from ajazz-hub.")

# Now, read the existing models.json from ajazz-driver-reverse
models_json_path = "models.json"
if not os.path.exists(models_json_path) and os.path.exists("ajazz-driver-reverse/models.json"):
    models_json_path = "ajazz-driver-reverse/models.json"

existing_models = []
if os.path.exists(models_json_path):
    try:
        with open(models_json_path, "r", encoding="utf-8") as f:
            existing_models = json.load(f)
        print(f"Loaded {len(existing_models)} existing models from {models_json_path}")
    except Exception as e:
        print(f"Error loading {models_json_path}: {e}")

# Mark existing models with driverSource = "driveall"
for m in existing_models:
    if "driverSource" not in m:
        m["driverSource"] = "driveall"

# Merge lists by checking duplicate (vendorId, productId, name)
merged_models = list(existing_models)
for hm in hub_models:
    # Check if there is an exact match in merged
    duplicate = False
    for em in merged_models:
        if em["vendorId"] == hm["vendorId"] and em["productId"] == hm["productId"] and em["name"] == hm["name"]:
            # If exists under driveall, we can annotate it or leave it, but let's update driverSource to "both" or keep both
            em["driverSource"] = "both"
            duplicate = True
            break
    if not duplicate:
        merged_models.append(hm)

# Sort merged list
merged_models.sort(key=lambda r: (r["driverSource"], r["name"], r["productId"]))

# Write merged_models back to models.json
try:
    with open(models_json_path, "w", encoding="utf-8") as f:
        json.dump(merged_models, f, ensure_ascii=False, indent=2)
    print(f"Successfully wrote {len(merged_models)} merged models to {models_json_path}")
except Exception as e:
    print(f"Error writing models.json: {e}")

# Generate models.ts in the appropriate location
models_ts_path = "src/protocol/models.ts"
if not os.path.exists("src/protocol") and os.path.exists("ajazz-driver-reverse/src/protocol"):
    models_ts_path = "ajazz-driver-reverse/src/protocol/models.ts"

body = json.dumps(merged_models, ensure_ascii=False, indent=2)
ts_content = f"""// AUTO-GENERATED by extract_hub_models.py.
// Do not hand-edit; re-run the extractor to merge driveall and ajazz-hub models.

export interface KeyboardModel {{
  vendorId: number;
  productId: number;
  name: string;
  supplierName: string;
  /** "USB" | "2.4G" | ... — transport this entry describes. */
  connectType: string;
  /** UI feature areas this model exposes. */
  routesName: string[];
  /** Keyboard render image filename under cache/static/keyboards/ (may be null). */
  keyboardImg: string | null;
  driverSource: "driveall" | "hub" | "both";
  deviceMode?: number;
}}

export const KEYBOARD_MODELS: KeyboardModel[] = {body};

/** Look up a model by USB vendor/product id (first match). */
export function findModel(vendorId: number, productId: number): KeyboardModel | undefined {{
  return KEYBOARD_MODELS.find((m) => m.vendorId === vendorId && m.productId === productId);
}}
"""

try:
    os.makedirs(os.path.dirname(models_ts_path), exist_ok=True)
    with open(models_ts_path, "w", encoding="utf-8") as f:
        f.write(ts_content)
    print(f"Successfully wrote TS models to {models_ts_path}")
except Exception as e:
    print(f"Error writing {models_ts_path}: {e}")
